# Generated by Django 4.0.9 on 2023-02-19 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phase1', models.CharField(max_length=50)),
                ('phase2', models.CharField(max_length=50)),
                ('phase3', models.CharField(max_length=50)),
                ('phase4', models.CharField(max_length=50)),
                ('phase5', models.CharField(max_length=50)),
                ('phase6', models.CharField(max_length=50)),
                ('phase7', models.CharField(max_length=50)),
                ('phase8', models.CharField(max_length=50)),
                ('phase9', models.CharField(max_length=50)),
                ('phase10', models.CharField(max_length=50)),
                ('phase11', models.CharField(max_length=50)),
                ('phase12', models.CharField(max_length=50)),
                ('phase13', models.CharField(max_length=50)),
                ('phase14', models.CharField(max_length=50)),
                ('phase15', models.CharField(blank=True, max_length=50)),
                ('phase16', models.CharField(blank=True, max_length=50)),
                ('phase17', models.CharField(blank=True, max_length=50)),
                ('phase18', models.CharField(blank=True, max_length=50)),
                ('phase19', models.CharField(blank=True, max_length=50)),
                ('phase20', models.CharField(blank=True, max_length=50)),
                ('phase21', models.CharField(blank=True, max_length=50)),
                ('phase22', models.CharField(blank=True, max_length=50)),
                ('phase23', models.CharField(blank=True, max_length=50)),
                ('phase24', models.CharField(blank=True, max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.account', verbose_name='auth account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
